name: Continuous Deployment

on:
  push:
    branches:
      - master
      - production
  pull_request:
    branches:
      - master
      - production
    

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Test and Lint
        run: docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test && flake8"

  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.12.21
      - name: Validate Terraform
        run: |
          cd deploy/
          terraform init -backend=false
          terraform validate -no-color
          terraform fmt -check

  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Buid and Push
        env:
          ECR_REPO: ${{ secrets.ECR_REPO }}
          COMMIT_SHORT_SHA: ${{ github.sha::8 }}
        run: |
          docker build --compress -t $ECR_REPO:$COMMIT_SHORT_SHA .
          docker push $ECR_REPO:$COMMIT_SHORT_SHA
          docker tag $ECR_REPO:$COMMIT_SHORT_SHA $ECR_REPO:latest
          docker push $ECR_REPO:latest

  plan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Plan Staging
        run: echo "Plan Staging"
      - name: Plan Production
        run: echo "Plan Production"
        if: github.ref == 'refs/heads/production'

  apply:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Apply Staging
        run: echo "Apply Staging"
      - name: Apply Production
        run: echo "Apply Production"
        if: github.ref == 'refs/heads/production'
        