name: Continuous Deployment

on:
  push:
    branches:
      - master
      - production
    

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Test and Lint
        run: echo "Test and Lint"

  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Validate Terraform
        run: echo "Validate Terraform"

  plan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Plan Staging
        run: echo "Plan Staging"
      - name: Plan Production
        run: echo "Plan Production"
        if: github.ref == 'refs/heads/production'

  apply:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Apply Staging
        run: echo "Apply Staging"
      - name: Apply Production
        run: echo "Apply Production"
        if: github.ref == 'refs/heads/production'
        